// components/GeneratePdf.jsx
import { jsPDF } from "jspdf";
import { Button } from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';

const GeneratePdf = ({ data }) => {
  const generatePDF = () => {
    const doc = new jsPDF();

    // Establecer fuente para el título
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);  // Tamaño de la fuente para el título
    doc.text("Spotify Listening Recap", 20, 20);

    // Título con fondo y borde
    doc.text("Total Stats", 20, 40); // Título de la sección de totales

    // Restablecer color del texto
    doc.setTextColor(0, 0, 0);

    // Añadir los totales con formato
    doc.setFontSize(12);  // Tamaño de la fuente para el texto normal
    
    // Total Plays
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Plays:`, 20, 50);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.totalPlays}`, 70, 50);

    // Total Minutes
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Minutes:`, 20, 55); // Reducir la distancia entre líneas
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.totalMinutes}`, 70, 55);

    // Total Hours
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Hours:`, 20, 60); // Reducir la distancia entre líneas
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.totalHours}`, 70, 60);

    // Total Days
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Days:`, 20, 65); // Reducir la distancia entre líneas
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.totalDays}`, 70, 65);

    // Agregar una línea divisoria
    doc.setLineWidth(0.5);
    doc.line(10, 75, 200, 75); // Línea divisoria

    // Establecer posición dinámica para las canciones
    let currentY = 85;

    // Añadir las canciones más escuchadas
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);  // Títulos de la sección de canciones
    doc.text("Top 10 Most Listened Songs", 20, currentY);
    doc.setFont('helvetica', 'normal');
    currentY += 8; // Reducir el espacio entre título y contenido

    data.topSongs.forEach((song, index) => {
      doc.text(`${index + 1}. ${song[0]} - ${song[1]} plays`, 20, currentY);
      currentY += 6; // Reducir el espaciado para cada canción
    });

    // Agregar otra línea divisoria después de las canciones
    doc.line(10, currentY, 200, currentY); // Línea divisoria
    currentY += 5; // Dejar espacio después de la línea

    // Añadir los artistas más escuchados
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);  // Títulos de la sección de artistas
    doc.text("Top 10 Most Listened Artists", 20, currentY);
    doc.setFont('helvetica', 'normal');
    currentY += 8; // Reducir el espacio entre título y contenido

    data.topArtists.forEach((artist, index) => {
      doc.text(`${index + 1}. ${artist[0]} - ${artist[1]} plays`, 20, currentY);
      currentY += 6; // Reducir el espaciado para cada artista
    });

    // Añadir una pequeña nota o pie de página
    doc.setFontSize(10); // Tamaño de fuente para el pie de página
    doc.text("Generated by TrackTrac", 150, currentY + 10);

    // Guardar el PDF
    doc.save("Spotify_Recap.pdf");
  };

  return (
    <Button 
      variant="contained" 
      color="primary" 
      onClick={generatePDF} 
      startIcon={<DownloadIcon />} 
      sx={{ marginTop: "20px", padding: "10px 20px", fontSize: "16px", borderRadius: 4 }}
    >
      Download PDF
    </Button>
  );
};

export default GeneratePdf;
